apiVersion: v1
kind: Service
metadata:
  name: tekmek-admin-product-manager-service
spec:
  type: NodePort
  selector:
    app: admin-product-manager
  ports:
    - name: admin-product-manager
      protocol: TCP
      port: 3000
      targetPort: 3000