CREATE TABLE IF NOT EXISTS `products_db`.`products_tb` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `image_url` VARCHAR(500) NULL DEFAULT NULL,
  `layout_size` VARCHAR(50) NULL DEFAULT NULL,
  `connectivity` VARCHAR(50) NULL DEFAULT NULL,
  `product_type` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `keycaps_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))