apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekmek-admin-product-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-product-manager
  template:
    metadata:
      labels:
        app: admin-product-manager
    spec:
      containers:
        - name: admin-product-manager
          image: quazmo/tekmek-admin-product-manager
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tekmek-admin-product-manager-clusterip-service
spec:
  selector:
    app: admin-product-manager
  ports:
    - name: admin-product-manager
      protocol: TCP
      port: 3000
      targetPort: 3000
