apiVersion: v1
kind: Service
metadata:
  name: tekmek-search-products-service
spec:
  type: NodePort
  selector:
    app: search-products
  ports:
    - name: search-products
      protocol: TCP
      port: 5240
      targetPort: 5240